language: objective-c
before_install:
  - gem install xcpretty
  - gem install cocoapods
  - pod install
script:  xcodebuild -workspace pop.xcworkspace -scheme pop -sdk iphonesimulator7.0 test | xcpretty -c
